---
version: 2
sources:
- name: "WESTPAC.RAW"
  database: "WESTPAC"
  schema: "RAW"
  config:
    enabled: true
  tables:
  - name: "RULE_ID_MAPPING"
    columns:
    - name: "EFS_HOUSING_PURPOSE"
      dataType:
        type: "String"
    - name: "EFS_HOUSING_PURPOSE_RULE_ID"
      dataType:
        type: "String"
    - name: "RULE_NAME"
      dataType:
        type: "String"
  - name: "PRODUCT_SYSTEM"
    columns:
    - name: "FROM_DATE"
      dataType:
        type: "Date"
    - name: "TO_DATE"
      dataType:
        type: "Date"
    - name: "ACCOUNT_ID"
      dataType:
        type: "Number"
    - name: "SRC_SYS_CODE"
      dataType:
        type: "String"
    - name: "PRODUCT_CODE"
      dataType:
        type: "Number"
    - name: "GL_ACCOUNT_ID"
      dataType:
        type: "Number"
    - name: "LEGAL_ENTITY_ID"
      dataType:
        type: "Number"
    - name: "CURRENT_BALANCE"
      dataType:
        type: "Float"
    - name: "MATURITY_DATE"
      dataType:
        type: "Date"
    - name: "OPENED_DATE"
      dataType:
        type: "Date"
    - name: "CURRENCY"
      dataType:
        type: "String"
  - name: "ORIGINATION_SYSTEM"
    columns:
    - name: "FROM_DATE"
      dataType:
        type: "Date"
    - name: "TO_DATE"
      dataType:
        type: "Date"
    - name: "APPIN_ID"
      dataType:
        type: "Number"
    - name: "SRC_SYS_CD"
      dataType:
        type: "String"
    - name: "PRIM_PURPS_TYPE_LBL"
      dataType:
        type: "String"
    - name: "SECND_PURPS_TYPE_LBL"
      dataType:
        type: "Number"
    - name: "CRNCY_CODE"
      dataType:
        type: "String"
    - name: "APPRV_LMT_AMT"
      dataType:
        type: "Float"
    - name: "ACCOUNT_ID"
      dataType:
        type: "Number"
  - name: "LOAN_PURPOSE"
    columns:
    - name: "SRC_SYS_CD"
      dataType:
        type: "String"
    - name: "SRC_LENDING_PURPOSE_CD"
      dataType:
        type: "Number"
    - name: "SRC_LENDING_PURPOSE_DESC"
      dataType:
        type: "String"
    - name: "PREDOMINANT_PURPOSE"
      dataType:
        type: "String"
    - name: "HOUSING_PURPOSE"
      dataType:
        type: "String"
    - name: "SUB_PURPOSE_HOUSING"
      dataType:
        type: "String"
    - name: "SUB_PURPOSE_PERSONAL"
      dataType:
        type: "String"
    - name: "SUB_PURPOSE_BUSINESS"
      dataType:
        type: "String"
    - name: "SUB_PURPOSE_LEASES"
      dataType:
        type: "String"
