WITH ORIGINATION_SYSTEM AS (

  SELECT * 
  
  FROM {{ source('WESTPAC.RAW', 'ORIGINATION_SYSTEM') }}

),

LOAN_PURPOSE AS (

  SELECT * 
  
  FROM {{ source('WESTPAC.RAW', 'LOAN_PURPOSE') }}

),

loan_purpose_details AS (

  {#Extracts loan purpose details including lending purpose codes, descriptions, predominant purpose, and sub-purposes for housing, personal, business, and leases.#}
  SELECT 
    SRC_SYS_CD AS SRC_SYS_CD,
    SRC_LENDING_PURPOSE_CD AS " Secnd_Purps_Type_Lbl",
    SRC_LENDING_PURPOSE_DESC AS SRC_LENDING_PURPOSE_DESC,
    PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    HOUSING_PURPOSE AS HOUSING_PURPOSE,
    SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    SUB_PURPOSE_PERSONAL AS SUB_PURPOSE_PERSONAL,
    SUB_PURPOSE_BUSINESS AS SUB_PURPOSE_BUSINESS,
    SUB_PURPOSE_LEASES AS SUB_PURPOSE_LEASES,
    1 AS EFS_Housing_purpose_Rule_ID
  
  FROM LOAN_PURPOSE

),

join_origination_loan_purpose AS (

  {#Combines origination system data with loan purpose details based on matching source system code and secondary purpose label.#}
  SELECT 
    in0.FROM_DATE AS FROM_DATE,
    in0.TO_DATE AS TO_DATE,
    in0.APPIN_ID AS APPIN_ID,
    in0.SRC_SYS_CD AS SRC_SYS_CD,
    in0.PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    in0.SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    in0.CRNCY_CODE AS CRNCY_CODE,
    in0.APPRV_LMT_AMT AS APPRV_LMT_AMT,
    in0.ACCOUNT_ID AS ACCOUNT_ID,
    in1.PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    in1.HOUSING_PURPOSE AS HOUSING_PURPOSE,
    in1.SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    in1.EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID
  
  FROM ORIGINATION_SYSTEM AS in0
  JOIN loan_purpose_details AS in1
     ON in0.SRC_SYS_CD = in1.SRC_SYS_CD and in0.SECND_PURPS_TYPE_LBL = in1." Secnd_Purps_Type_Lbl"

),

PRODUCT_SYSTEM AS (

  SELECT * 
  
  FROM {{ source('WESTPAC.RAW', 'PRODUCT_SYSTEM') }}

),

PRODUCT_SYSTEM_ORIGINATION_SYSTEM AS (

  {#Combines product system information with origination system details for analysis and comparison.#}
  SELECT 
    PRODUCT_SYSTEM.FROM_DATE AS FROM_DATE,
    PRODUCT_SYSTEM.TO_DATE AS TO_DATE,
    PRODUCT_SYSTEM.ACCOUNT_ID AS ACCOUNT_ID,
    PRODUCT_SYSTEM.SRC_SYS_CODE AS SRC_SYS_CODE,
    PRODUCT_SYSTEM.PRODUCT_CODE AS PRODUCT_CODE,
    PRODUCT_SYSTEM.GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    PRODUCT_SYSTEM.LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    PRODUCT_SYSTEM.CURRENT_BALANCE AS CURRENT_BALANCE,
    PRODUCT_SYSTEM.MATURITY_DATE AS MATURITY_DATE,
    PRODUCT_SYSTEM.OPENED_DATE AS OPENED_DATE,
    PRODUCT_SYSTEM.CURRENCY AS CURRENCY,
    ORIGINATION_SYSTEM.FROM_DATE AS FROM_DATE2,
    ORIGINATION_SYSTEM.TO_DATE AS TO_DATE2,
    ORIGINATION_SYSTEM.APPIN_ID AS APPIN_ID,
    ORIGINATION_SYSTEM.SRC_SYS_CD AS ORIGINATION_SYSTEM,
    ORIGINATION_SYSTEM.PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    ORIGINATION_SYSTEM.SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    ORIGINATION_SYSTEM.CRNCY_CODE AS CRNCY_CODE,
    ORIGINATION_SYSTEM.APPRV_LMT_AMT AS APPRV_LMT_AMT,
    ORIGINATION_SYSTEM.PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    ORIGINATION_SYSTEM.HOUSING_PURPOSE AS HOUSING_PURPOSE,
    ORIGINATION_SYSTEM.SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    ORIGINATION_SYSTEM.EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID
  
  FROM PRODUCT_SYSTEM
  INNER JOIN join_origination_loan_purpose AS ORIGINATION_SYSTEM
     ON PRODUCT_SYSTEM.ACCOUNT_ID = ORIGINATION_SYSTEM.ACCOUNT_ID

),

Add_EFS_Housing_Purpose_Rule AS (

  {#Reformats and extracts relevant information from the product system origination system.#}
  SELECT 
    FROM_DATE AS FROM_DATE,
    TO_DATE AS TO_DATE,
    ACCOUNT_ID AS ACCOUNT_ID,
    SRC_SYS_CODE AS SRC_SYS_CODE,
    PRODUCT_CODE AS PRODUCT_CODE,
    GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    CURRENT_BALANCE AS CURRENT_BALANCE,
    MATURITY_DATE AS MATURITY_DATE,
    OPENED_DATE AS OPENED_DATE,
    CURRENCY AS CURRENCY,
    FROM_DATE2 AS FROM_DATE2,
    TO_DATE2 AS TO_DATE2,
    APPIN_ID AS APPIN_ID,
    ORIGINATION_SYSTEM AS ORIGINATION_SYSTEM,
    PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    CRNCY_CODE AS CRNCY_CODE,
    APPRV_LMT_AMT AS APPRV_LMT_AMT,
    PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    HOUSING_PURPOSE AS HOUSING_PURPOSE,
    SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID,
    CASE
      WHEN SECND_PURPS_TYPE_LBL = '231' AND ORIGINATION_SYSTEM = 'MP-001' AND HOUSING_PURPOSE = 'OO'
        THEN 'IPL'
      ELSE HOUSING_PURPOSE
    END AS EFS_HOUSING_PURPOSE
  
  FROM PRODUCT_SYSTEM_ORIGINATION_SYSTEM AS in0

),

RULE_ID_MAPPING AS (

  SELECT * 
  
  FROM {{ source('WESTPAC.RAW', 'RULE_ID_MAPPING') }}

),

product_system_origination_system_1_RULE_ID_MAPPING AS (

  {#Maps product system origination data with corresponding rule IDs for EFS housing purpose.#}
  SELECT 
    CASE
      WHEN From_Date = last_day(From_Date)
        THEN From_Date
      ELSE last_day(dateadd(DAY, -30, From_Date))
    END AS PROCESS_DATE,
    product_system_origination_system_1.FROM_DATE AS FROM_DATE,
    product_system_origination_system_1.TO_DATE AS TO_DATE,
    product_system_origination_system_1.ACCOUNT_ID AS ACCOUNT_ID,
    product_system_origination_system_1.SRC_SYS_CODE AS PRODUCT_SYSTEM,
    product_system_origination_system_1.PRODUCT_CODE AS PRODUCT_CODE,
    product_system_origination_system_1.GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    product_system_origination_system_1.LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    product_system_origination_system_1.CURRENT_BALANCE AS CURRENT_BALANCE,
    product_system_origination_system_1.MATURITY_DATE AS MATURITY_DATE,
    product_system_origination_system_1.OPENED_DATE AS OPENED_DATE,
    product_system_origination_system_1.CURRENCY AS CURRENCY,
    product_system_origination_system_1.ORIGINATION_SYSTEM AS ORIGINATION_SYSTEM,
    product_system_origination_system_1.PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    product_system_origination_system_1.SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    product_system_origination_system_1.APPRV_LMT_AMT AS APPRV_LMT_AMT,
    product_system_origination_system_1.PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    product_system_origination_system_1.EFS_HOUSING_PURPOSE AS EFS_HOUSING_PURPOSE,
    product_system_origination_system_1.SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    RULE_ID_MAPPING.EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID,
    product_system_origination_system_1.HOUSING_PURPOSE AS HOUSING_PURPOSE
  
  FROM Add_EFS_Housing_Purpose_Rule AS product_system_origination_system_1
  INNER JOIN RULE_ID_MAPPING
     ON RULE_ID_MAPPING.EFS_HOUSING_PURPOSE = product_system_origination_system_1.EFS_HOUSING_PURPOSE

),

Reformat_1 AS (

  {#Reformats and extracts relevant information from the product system origination system mapping table.#}
  SELECT 
    PROCESS_DATE AS PROCESS_DATE,
    FROM_DATE AS FROM_DATE,
    TO_DATE AS TO_DATE,
    ACCOUNT_ID AS ACCOUNT_ID,
    PRODUCT_SYSTEM AS PRODUCT_SYSTEM,
    PRODUCT_CODE AS PRODUCT_CODE,
    GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    CURRENT_BALANCE AS CURRENT_BALANCE,
    MATURITY_DATE AS MATURITY_DATE,
    OPENED_DATE AS OPENED_DATE,
    CURRENCY AS CURRENCY,
    ORIGINATION_SYSTEM AS ORIGINATION_SYSTEM,
    PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    APPRV_LMT_AMT AS APPRV_LMT_AMT,
    PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    EFS_HOUSING_PURPOSE AS EFS_HOUSING_PURPOSE,
    SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID,
    DATEDIFF(DAY, PROCESS_DATE, MATURITY_DATE) AS RESIDUAL_DAYS,
    DATEDIFF(DAY, PROCESS_DATE, MATURITY_DATE) / 365 AS RESIDUAL_YEARS,
    HOUSING_PURPOSE AS HOUSING_PURPOSE
  
  FROM product_system_origination_system_1_RULE_ID_MAPPING

),

Reformat_2 AS (

  {#Reformats and extracts relevant information from a dataset containing account details, including balance, maturity date, currency, and purpose.#}
  SELECT 
    PROCESS_DATE AS PROCESS_DATE,
    FROM_DATE AS FROM_DATE,
    TO_DATE AS TO_DATE,
    ACCOUNT_ID AS ACCOUNT_ID,
    PRODUCT_SYSTEM AS PRODUCT_SYSTEM,
    PRODUCT_CODE AS PRODUCT_CODE,
    GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    CURRENT_BALANCE AS CURRENT_BALANCE,
    MATURITY_DATE AS MATURITY_DATE,
    OPENED_DATE AS OPENED_DATE,
    CURRENCY AS CURRENCY,
    ORIGINATION_SYSTEM AS ORIGINATION_SYSTEM,
    PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    APPRV_LMT_AMT AS APPRV_LMT_AMT,
    PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    EFS_HOUSING_PURPOSE AS EFS_HOUSING_PURPOSE,
    SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID,
    RESIDUAL_DAYS AS RESIDUAL_DAYS,
    RESIDUAL_YEARS AS RESIDUAL_YEARS,
    CASE
      WHEN Residual_years > 0 and Residual_years < 1
        THEN 'Short Term'
      WHEN Residual_years > 1
        THEN 'Long Term'
      ELSE 'Long Term'
    END AS EFS_RESIDUAL_TERM,
    HOUSING_PURPOSE AS HOUSING_PURPOSE
  
  FROM Reformat_1 AS in0

),

Reformat_3 AS (

  {#Reformats and extracts relevant information from the input dataset, including various account details and calculated residual term rule.#}
  SELECT 
    PROCESS_DATE AS PROCESS_DATE,
    FROM_DATE AS FROM_DATE,
    TO_DATE AS TO_DATE,
    ACCOUNT_ID AS ACCOUNT_ID,
    PRODUCT_SYSTEM AS PRODUCT_SYSTEM,
    PRODUCT_CODE AS PRODUCT_CODE,
    GL_ACCOUNT_ID AS GL_ACCOUNT_ID,
    LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID,
    CURRENT_BALANCE AS CURRENT_BALANCE,
    MATURITY_DATE AS MATURITY_DATE,
    OPENED_DATE AS OPENED_DATE,
    CURRENCY AS CURRENCY,
    ORIGINATION_SYSTEM AS ORIGINATION_SYSTEM,
    PRIM_PURPS_TYPE_LBL AS PRIM_PURPS_TYPE_LBL,
    SECND_PURPS_TYPE_LBL AS SECND_PURPS_TYPE_LBL,
    APPRV_LMT_AMT AS APPRV_LMT_AMT,
    PREDOMINANT_PURPOSE AS PREDOMINANT_PURPOSE,
    EFS_HOUSING_PURPOSE AS EFS_HOUSING_PURPOSE,
    SUB_PURPOSE_HOUSING AS SUB_PURPOSE_HOUSING,
    EFS_HOUSING_PURPOSE_RULE_ID AS EFS_HOUSING_PURPOSE_RULE_ID,
    RESIDUAL_DAYS AS RESIDUAL_DAYS,
    RESIDUAL_YEARS AS RESIDUAL_YEARS,
    EFS_RESIDUAL_TERM AS EFS_RESIDUAL_TERM,
    HOUSING_PURPOSE AS HOUSING_PURPOSE,
    CASE
      WHEN RESIDUAL_YEARS > 0 AND RESIDUAL_YEARS <= 1
        THEN 5
      WHEN RESIDUAL_YEARS > 1
        THEN 6
      WHEN MATURITY_DATE IS NULL
        THEN 7
      ELSE NULL
    END AS EFS_RESIDUAL_TERM_RULE_ID
  
  FROM Reformat_2 AS in0

)

SELECT *

FROM Reformat_3
